CREATE DATABASE photostory;

USE photostory;

-- ---
-- Table 'Users'
-- 
-- ---
		
CREATE TABLE `Users` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `Username` CHAR NULL DEFAULT NULL,
  `Name` CHAR NULL DEFAULT NULL,
  `Profile Pic` CHAR NULL DEFAULT NULL,
  `Bio` CHAR NULL DEFAULT NULL,
  `Email` CHAR NULL DEFAULT NULL,
  `Friend List ID` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'Posts'
-- 
-- ---

DROP TABLE IF EXISTS `Posts`;
		
CREATE TABLE `Posts` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `User ID` INTEGER NULL DEFAULT NULL,
  `Likes` CHAR NULL DEFAULT NULL,
  `Description` CHAR NULL DEFAULT NULL,
  `photo` CHAR NULL DEFAULT NULL,
  `location` CHAR NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'Comments'
-- 
-- ---

DROP TABLE IF EXISTS `Comments`;
		
CREATE TABLE `Comments` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `Text` CHAR NULL DEFAULT NULL,
  `User ID` INTEGER NULL DEFAULT NULL,
  `Post ID` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'Friends'
-- 
-- ---

DROP TABLE IF EXISTS `Friends`;
		
CREATE TABLE `Friends` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `Friend ID` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);


